language: python
addons:
  apt:
    packages:
    - octave
  
matrix:
  include:
  - os: linux
  python:
  - "3.7"
  
  

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y octave liboctave-dev libnetcdf-dev netcdf-bin gnuplot octave-statistics
  
install:
  - pip install scipy
  
  
script:
  - octave-cli --no-gui --eval "pkg load statistics"
  - octave-cli lab2MATHPACK.m
  - python -m unittest -v Test_for_mp_lab2.py


